# ***********************************************************************
# ETF Hash: values are inverse ETFs
# ***********************************************************************

ETF_HASH = {     'TQQQ' : 'SQQQ',
                 'SPY'  : 'SH',
                 'DDM'  : 'DXD',
                 'MVV'  : 'MZZ',
                 'UWM'  : 'TWM',
                 'SAA'  : 'SDD',
                 'UYM'  : 'SMN',
                 'UGE'  : 'SZK',
                 'UCC'  : 'SCC',
                 'FINU' : 'FINZ',
                 'RXL'  : 'RXD',
                 'UXI'  : 'SIJ',
                 'URE'  : 'SRS',
                 'ROM'  : 'REW',
                 'UJB'  : 'SJB',
                 'AGQ'  : 'ZSL',     
                 'DIG'  : 'DUG',
                 'USD'  : 'SSG',
                 'ERX'  : 'ERY',
                 'UYG'  : 'SKF',
                 'UCO'  : 'SCO',
                 'BOIL' : 'KOLD',
                 'UPW'  : 'SDP',
                 'UGL'  : 'GLL',
                 'BIB'  : 'BIS',
                 'UST'  : 'PST',
                 'UBT'  : 'TBT' }

SUB_ETF_HASH = { 'TQQQ' : 'SQQQ',
                 'ROM'  : 'REW',
                 'UGL'  : 'GLL',
                 'BOIL' : 'KOLD',
                 'SPY'  : 'SH',
                 'UCO'  : 'SCO',
                 'ERX'  : 'ERY',
                 'DIG'  : 'DUG',
                 'USD'  : 'SSG',
                 'UBT'  : 'TBT',
                 'BIB'  : 'BIS',
                 'AGQ'  : 'ZSL',
                 'DDM'  : 'DXD',
                 'UWM'  : 'TWM',
                 'UYG'  : 'SKF',
                 'MVV'  : 'MZZ'    }

NEW_ETF_HASH = { 'TQQQ' : 'SQQQ',
                 'SPY'  : 'SH',
                 'DDM'  : 'DXD',
                 'MDY'  : 'MYY',
                 'UWM'  : 'TWM',
                 'IJS'  : 'SBB',
                 'XLP'  : 'SZK',
                 'FAS'  : 'FAZ',    
                 'CURE' : 'RXD',
                 'XLI'  : 'SIJ',    
                 'DIA'  : 'DOG',    
                 'XLRE' : 'SRS',
                 'MUB'  : 'SAGG',    
                 'TECL' : 'TECS',
                 'HYG'  : 'SJB',
                 'AGQ'  : 'ZSL',     
                 'SOXX' : 'SSG',
                 'ERX'  : 'ERY',
                 'UCO'  : 'SCO',
                 'BOIL' : 'KOLD',
                 'XLU'  : 'SDP',
                 'UGLD' : 'DGLD',    
                 'BIB'  : 'BIS',
                 'IEF'  : 'TBX',
                 'TLT'  : 'TBF',
                 'UVXY' : 'SVXY'  }

POP_ETF_HASH = { 'QQQ'  : 'PSQ',
                 'SPY'  : 'SH',
                 'DIA'  : 'DOG',
                 'MDY'  : 'MYY',
                 'IWM'  : 'RWM',
                 'OIH'  : 'SCO',
                 'SMH'  : 'SSG',
                 'TQQQ' : 'SQQQ',
                 'DDM'  : 'DXD',
                 'AGQ'  : 'ZSL',
                 'ERX'  : 'ERY',
                 'UCO'  : 'SCO',
                 'BOIL' : 'KOLD',
                 'BIB'  : 'BIS',
                 'NUGT' : 'DUST',
                 'FREL' : 'REK'   }

# ***********************************************************************
# ETFs for options
# ***********************************************************************

OPTION_ETFS = [ 'QQQ',
                'SPY',
                'DIA',
                'MDY',
                'IWM',
                'OIH',
                'SMH',
                'XLU',
                'EWJ' ]

PI_ETFS = [ 'QQQ',
            'SPY',
            'DIA',
            'MDY',
            'IWM',
            'BBH',
            'GDX',
            'OIH',
            'PPH',
            'RTH',
            'RSX',
            'SMH',
            'XLC',
            'XLE',
            'XLF',
            'XLV',
            'XLU',
            'FXI',
            'TLT',
            'EEM',
            'EWJ',
            'IYR',
            'FXE',
            'SDS',
            'VXX',
            'SLV',
            'GLD',
            'USO',
            'UNG',
            'TNA',
            'TZA',
            'FAS',
            'FAZ'  ]
    
# ***********************************************************************
# Futures
# ***********************************************************************

FUTURES = [ 'ES',
            'NQ',
            'US',
            'YM',
            'RTY',
            'EMD',
            'QM'  ]

# ***********************************************************************
# Indexes
# ***********************************************************************

INDEXES = [ 'NDX',
            'SPX',
            'RUT',
            'OEX',
            'MID',
            'SOX',
            'RUI',
            'RUA',
            'TRAN',
            'HGX',
            'TYX',
            'XAU' ]

PI_INDEXES = [  'NDX',
                'SPX',
                'RUT',
                'OEX',
                'MID',
                'SOX',
                'RUI',
                'RUA',
                'TRAN',
                'HGX',
                'TYX',
                'VIX',
                'VXN',
                'HUI',
                'XAU' ]
